name: CrystalMistral CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
